Repository zanfranceschi/rinha-de-backend-2025, pull requests merged in 2025-08, with the labels that each got.

#885 Updating dolphs
  participantes/dolphs/Caddyfile
  participantes/dolphs/README.md
  participantes/dolphs/docker-compose.logs
  participantes/dolphs/docker-compose.yml
  participantes/dolphs/haproxy/haproxy.cfg
  participantes/dolphs/info.json
  participantes/dolphs/k6.logs
  participantes/dolphs/nginx.conf
  participantes/dolphs/partial-results.json
Labels: RESOLVER CONFLITO

#932 Enviando participacao caiodgallo-go
  participantes/caiodgallo-go/README.md
  participantes/caiodgallo-go/docker-compose.yml
  participantes/caiodgallo-go/haproxy.cfg
  participantes/caiodgallo-go/info.json
  participantes/caiodgallo-go/postgresql.conf
Labels: SUBMISSÃO INVÁLIDA

#975 chore(josineyjr): retest
  participantes/josineyjr-go-2/docker-compose.logs
  participantes/josineyjr-go-2/docker-compose.yml
  participantes/josineyjr-go-2/haproxy.cfg
  participantes/josineyjr-go-2/k6.logs
  participantes/josineyjr-go-2/partial-results.json
  participantes/josineyjr-go-3/docker-compose.logs
  participantes/josineyjr-go-3/docker-compose.yml
  participantes/josineyjr-go-3/haproxy.cfg
  participantes/josineyjr-go-3/k6.logs
  participantes/josineyjr-go-3/partial-results.json
Labels: SUBMISSÃO INVÁLIDA

#977 Update Docker image version and enhance configuration settings
  participantes/joelgarciajr84-go/docker-compose.logs
  participantes/joelgarciajr84-go/docker-compose.yml
  participantes/joelgarciajr84-go/info.json
  participantes/joelgarciajr84-go/k6.logs
  participantes/joelgarciajr84-go/nginx.conf
  participantes/joelgarciajr84-go/partial-results.json
Labels: SUBMISSÃO INVÁLIDA

#988 add-participante:wallacemendes
  participantes/wallacemendes-node/README.md
  participantes/wallacemendes-node/docker-compose.yml
  participantes/wallacemendes-node/info.json
  participantes/wallacemendes-node/nginx.conf
Labels: GOOD TO GO

#987 20250802001327
  participantes/joaoprocopio/docker-compose.logs
  participantes/joaoprocopio/docker-compose.yaml
  participantes/joaoprocopio/k6.logs
  participantes/joaoprocopio/partial-results.json
Labels: GOOD TO GO

#985 feat: participante igor-gregori-bun-v1
  participantes/igor-gregori-bun-v1/README.md
  participantes/igor-gregori-bun-v1/docker-compose.yml
  participantes/igor-gregori-bun-v1/info.json
  participantes/igor-gregori-bun-v1/nginx.conf
Labels: GOOD TO GO

#983 retest
  participantes/dudebank-bun/.env
  participantes/dudebank-bun/docker-compose.logs
  participantes/dudebank-bun/docker-compose.yml
  participantes/dudebank-bun/info.json
  participantes/dudebank-bun/k6.logs
  participantes/dudebank-bun/nginx.conf
  participantes/dudebank-bun/partial-results.json
Labels: GOOD TO GO

#1180 add submission v1
  participantes/carlos-demarco/README.md
  participantes/carlos-demarco/docker-compose.yml
  participantes/carlos-demarco/info.json
  participantes/carlos-demarco/nginx.conf
Labels: SUBMISSÃO INVÁLIDA

#1183 feat - cpp submission
  participantes/mxlange-cpp/README.md
  participantes/mxlange-cpp/docker-compose.yml
  participantes/mxlange-cpp/info.json
  participantes/mxlange-cpp/nginx.conf
Labels: SUBMISSÃO INVÁLIDA

#1223 remove partial sylviot
  participantes/sylviot/docker-compose.logs
  participantes/sylviot/k6.logs
  participantes/sylviot/partial-results.json
Labels: GOOD TO GO

#1222 retest: update jjeanjacques10 to use rinhabackend2025:graalvm-v3.0
  participantes/jjeanjacques10/README.md
  participantes/jjeanjacques10/docker-compose.logs
  participantes/jjeanjacques10/docker-compose.yml
  participantes/jjeanjacques10/info.json
  participantes/jjeanjacques10/k6.logs
  participantes/jjeanjacques10/partial-results.json
Labels: GOOD TO GO

#1234 submit flads-go project
  participantes/flads-go/README.md
  participantes/flads-go/docker-compose.yml
  participantes/flads-go/info.json
  participantes/flads-go/nginx/nginx.conf
Labels: GOOD TO GO

#1235 retest: lucas lima chaves
  participantes/lucas-lima-chaves/docker-compose.logs
  participantes/lucas-lima-chaves/k6.logs
  participantes/lucas-lima-chaves/nginx.conf
  participantes/lucas-lima-chaves/partial-results.json
Labels: GOOD TO GO

#1236 player456 - retry 4
  participantes/boaglio-player456/docker-compose.logs
  participantes/boaglio-player456/docker-compose.yaml
  participantes/boaglio-player456/k6.logs
  participantes/boaglio-player456/partial-results.json
Labels: GOOD TO GO

#1237 Update image to 2.2.3
  participantes/marcosmarcolin-php/docker-compose.logs
  participantes/marcosmarcolin-php/docker-compose.yml
  participantes/marcosmarcolin-php/k6.logs
  participantes/marcosmarcolin-php/partial-results.json
Labels: GOOD TO GO

#1054 versao nova que funciona
  participantes/diofeher/docker-compose.logs
  participantes/diofeher/docker-compose.yml
  participantes/diofeher/error.logs
  participantes/diofeher/nginx.conf
  participantes/diofeher/partial-results.json
Labels: SUBMISSÃO INVÁLIDA

#1533 Submissao vitorvale nestjs
  participantes/vitor-vale/README.md
  participantes/vitor-vale/docker-compose.yml
  participantes/vitor-vale/info.json
  participantes/vitor-vale/init.sql
  participantes/vitor-vale/nginx.conf
Labels: GOOD TO GO

#1544 Ultima pra vir prod com força
  participantes/mdantas-rust/docker-compose.logs
  participantes/mdantas-rust/docker-compose.yaml
  participantes/mdantas-rust/k6.logs
  participantes/mdantas-rust/partial-results.json
Labels: RESOLVER CONFLITO

#1638 retest
  participantes/pedrohsb-golang/docker-compose.logs
  participantes/pedrohsb-golang/docker-compose.yml
  participantes/pedrohsb-golang/k6.logs
  participantes/pedrohsb-golang/partial-results.json
Labels: SUBMISSÃO INVÁLIDA

#1646 update Thomaz golang
  participantes/thomaz-maldonado-go-1/docker-compose.logs
  participantes/thomaz-maldonado-go-1/k6.logs
  participantes/thomaz-maldonado-go-1/partial-results.json
Labels: SUBMISSÃO INVÁLIDA

#1641 20250807093812
  participantes/joaoprocopio/docker-compose.logs
  participantes/joaoprocopio/docker-compose.yaml
  participantes/joaoprocopio/partial-results.json
Labels: RESOLVER CONFLITO

#1703 retest
  participantes/gabrieleiro/docker-compose.logs
  participantes/gabrieleiro/docker-compose.yml
  participantes/gabrieleiro/k6.logs
  participantes/gabrieleiro/partial-results.json
Labels: GOOD TO GO

#1706 nova submissão
  participantes/joaoulian/README.md
  participantes/joaoulian/docker-compose.logs
  participantes/joaoulian/docker-compose.yml
  participantes/joaoulian/haproxy.cfg
  participantes/joaoulian/info.json
  participantes/joaoulian/k6.logs
  participantes/joaoulian/nginx.conf
  participantes/joaoulian/partial-results.json
Labels: GOOD TO GO

#1709 [rodrigo-militao-v2] resubimission
  participantes/rodrigo-militao-v2/docker-compose.logs
  participantes/rodrigo-militao-v2/k6.logs
  participantes/rodrigo-militao-v2/partial-results.json
Labels: GOOD TO GO

#1705 submetendo minha solucao para rinha
  participantes/developerarthur/README.md
  participantes/developerarthur/docker-compose.yaml
  participantes/developerarthur/info.json
  participantes/developerarthur/init-mydb.sql
  participantes/developerarthur/nginx.conf
Labels: GOOD TO GO

#1823 Primeira Submissão
  participantes/juanlimalf-python-fastapi/README.md
  participantes/juanlimalf-python-fastapi/docker-compose.yaml
  participantes/juanlimalf-python-fastapi/info.json
  participantes/juanlimalf-python-fastapi/nginx.conf
Labels: SUBMISSÃO INVÁLIDA

#2032 testando native com socket
  participantes/marcelo-dias/docker-compose.logs
  participantes/marcelo-dias/docker-compose.yml
  participantes/marcelo-dias/haproxy.cfg
  participantes/marcelo-dias/k6.logs
  participantes/marcelo-dias/partial-results.json
Labels: GOOD TO GO

#2034 new submission
  participantes/lucas-moraes/README.md
  participantes/lucas-moraes/docker-compose.yml
  participantes/lucas-moraes/info.json
  participantes/lucas-moraes/nginx.conf
Labels: GOOD TO GO

#2027 feat: retest jjeanjacques10 fix container memory
  participantes/jjeanjacques10/README.md
  participantes/jjeanjacques10/docker-compose.logs
  participantes/jjeanjacques10/docker-compose.yml
  participantes/jjeanjacques10/k6.logs
  participantes/jjeanjacques10/partial-results.json
Labels: GOOD TO GO

#2028 add davidalecrim1 ajuste na versao 4
  participantes/davidalecrim1-go-4/docker-compose.logs
  participantes/davidalecrim1-go-4/docker-compose.yml
  participantes/davidalecrim1-go-4/k6.logs
  participantes/davidalecrim1-go-4/partial-results.json
Labels: GOOD TO GO

#2030 alter lucas-go-01
  participantes/lucas-go-01/docker-compose.logs
  participantes/lucas-go-01/error.logs
  participantes/lucas-go-01/partial-results.json
Labels: GOOD TO GO

#2035 update docker image e re-run
  participantes/lauro-santana-go/docker-compose.logs
  participantes/lauro-santana-go/docker-compose.yml
  participantes/lauro-santana-go/error.logs
  participantes/lauro-santana-go/partial-results.json
Labels: GOOD TO GO

#2038 Add asfernandes-boost-lmdb and retest asfernandes-haproxy-mongoose-lmdb
  participantes/asfernandes-boost-lmdb/.gitignore
  participantes/asfernandes-boost-lmdb/README.md
  participantes/asfernandes-boost-lmdb/docker-compose.yml
  participantes/asfernandes-boost-lmdb/info.json
  participantes/asfernandes-haproxy-mongoose-lmdb/docker-compose.logs
  participantes/asfernandes-haproxy-mongoose-lmdb/k6.logs
  participantes/asfernandes-haproxy-mongoose-lmdb/partial-results.json
Labels: GOOD TO GO

#2040 🐦 pru: a wild pidgeon appears (v1.0.0)
  participantes/pru/README.md
  participantes/pru/docker-compose.yml
  participantes/pru/info.json
  participantes/pru/init.sql
  participantes/pru/nginx.conf
Labels: GOOD TO GO

#2042 feat: testando otimizações.
  participantes/passos-matheus-python-timeout-adaptivo/docker-compose.logs
  participantes/passos-matheus-python-timeout-adaptivo/docker-compose.yml
  participantes/passos-matheus-python-timeout-adaptivo/k6.logs
  participantes/passos-matheus-python-timeout-adaptivo/partial-results.json
Labels: GOOD TO GO

#2046 fix: adjust resource limits
  participantes/lhuizf-bun/docker-compose.logs
  participantes/lhuizf-bun/docker-compose.yml
  participantes/lhuizf-bun/k6.logs
  participantes/lhuizf-bun/partial-results.json
Labels: GOOD TO GO

#2051 diogoloff-delphi
  participantes/diogoloff-delphi/README.md
  participantes/diogoloff-delphi/docker-compose.yml
  participantes/diogoloff-delphi/info.json
  participantes/diogoloff-delphi/nginx.conf
Labels: GOOD TO GO

#2212 adding a new worker
  participantes/mourishitz-go/docker-compose.logs
  participantes/mourishitz-go/docker-compose.yml
  participantes/mourishitz-go/k6.logs
  participantes/mourishitz-go/partial-results.json
Labels: SUBMISSÃO INVÁLIDA

#2875 Submissão rinha de backend
  participantes/igor-lucas-csharp/Readme.md
  participantes/igor-lucas-csharp/docker-compose.yaml
  participantes/igor-lucas-csharp/info.json
  participantes/igor-lucas-csharp/init.sql
  participantes/igor-lucas-csharp/nginx.conf
Labels: SUBMISSÃO INVÁLIDA

#2963 Rinha Backend 2025 submission by eduardofp17 - Node.js, TypeScript, R…
  participantes/eduardofp17-node/README.md
  participantes/eduardofp17-node/docker-compose.yaml
  participantes/eduardofp17-node/info.json
  participantes/eduardofp17-node/nginx.conf
Labels: SUBMISSÃO INVÁLIDA

#2979 Implementação em Object Pascal
  participantes/maico-smaniotto-objpas-pgsql/README.md
  participantes/maico-smaniotto-objpas-pgsql/db/init.sql
  participantes/maico-smaniotto-objpas-pgsql/db/postgresql.conf
  participantes/maico-smaniotto-objpas-pgsql/docker-compose.yml
  participantes/maico-smaniotto-objpas-pgsql/info.json
  participantes/maico-smaniotto-objpas-pgsql/nginx.conf
Labels: SUBMISSÃO INVÁLIDA

#3216 Rerun de submissões + nova sub com http module no memorydb
  participantes/cristian-s-node-1/docker-compose.logs
  participantes/cristian-s-node-1/k6.logs
  participantes/cristian-s-node-1/partial-results.json
  participantes/cristian-s-node-2-http/docker-compose.logs
  participantes/cristian-s-node-2-http/k6.logs
  participantes/cristian-s-node-2-http/partial-results.json
  participantes/cristian-s-node-3-http-2/README.md
  participantes/cristian-s-node-3-http-2/docker-compose.yml
  participantes/cristian-s-node-3-http-2/haproxy.cfg
  participantes/cristian-s-node-3-http-2/info.json
Labels: SUBMISSÃO INVÁLIDA
